name: Build
on: [push, workflow_dispatch]
jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install flet
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Force Create File and Build
        run: |
          # Мы сами создаем файл, чтобы робот его точно увидел
          cat <<EOF > main.py
          import flet as ft
          # ВСТАВЬ СВОЙ КОД НИЖЕ ЭТОЙ СТРОКИ
          def main(page: ft.Page):
              page.add(ft.Text("Работает!"))
          ft.app(target=main)
          EOF
          
          mkdir -p assets
          flet build apk --target main.py
      - uses: actions/upload-artifact@v4
        with:
          name: MyApp
          path: build/apk/*.apk
