name: Build
on: [push, workflow_dispatch]
jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install flet
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Auto-Build
        run: |
          # Ищем, где на самом деле лежит main.py
          REAL_PATH=$(find . -name "main.py" -not -path "*/.*" | head -n 1)
          echo "Файл найден по адресу: $REAL_PATH"
          # Создаем папку assets на всякий случай
          mkdir -p assets
          # Запускаем сборку
          flet build apk --target "$REAL_PATH"
      - uses: actions/upload-artifact@v4
        with:
          name: App
          path: build/apk/*.apk
