name: Build
on: [push, workflow_dispatch]
jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Поиск файлов
        run: |
          echo "Где я нахожусь:"
          pwd
          echo "Что лежит в этой папке:"
          ls -R
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install flet
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Сборка
        run: |
          # Эта команда попробует найти main.py везде
          FILE_PATH=$(find . -name "main.py" -print -quit)
          echo "Файл найден тут: $FILE_PATH"
          flet build apk --target "$FILE_PATH"
      - uses: actions/upload-artifact@v4
        with:
          name: App
          path: build/apk/*.apk
